---
# tasks file for cloud-init
- name: Cloud base package setup
  when: >
    ansible_distribution == 'CentOS'
    or
    ansible_distribution == 'Red Hat Enterprise Linux'
    or
    ansible_distribution == 'RedHat'
    or
    ansible_distribution == 'Amazon'
  yum: name={{ item }} state=latest
  become: yes
  with_items:
      - awscli.noarch
      - ansible.noarch
      - fail2ban
      - "@Development tools"
  tags: 
   - base-install

- name: fail2ban service  
  when: >
    ansible_distribution == 'CentOS'
    or
    ansible_distribution == 'Red Hat Enterprise Linux'
    or
    ansible_distribution == 'RedHat'
    or
    ansible_distribution == 'Amazon'
  service:
    name: fail2ban
    enabled: yes
    state: started 


