---
# tasks file for cloud-init
- name: Cloud base package setup
  when: >
    ansible_distribution == 'CentOS'
    or
    ansible_distribution == 'Red Hat Enterprise Linux'
    or
    ansible_distribution == 'RedHat'
    or
    ansible_distribution == 'Amazon'
  #yum: name={{ item }} state=latest
  yum: 
    name: ['awscli.noarch', 'fail2ban', '@Development tools']
    state: latest
  become: yes
  #with_items:
  #    - awscli.noarch
  #    - ansible.noarch
  #    - fail2ban
  #    - "@Development tools"
  notify:
  - fali2ban | Started
  tags: 
   - base-install


- name: fail2ban config 
  when: >
    ansible_distribution == 'centos'
    or
    ansible_distribution == 'Red Hat Enterprise Linux'
    or 
    ansible_distribution == 'RedHat'
    or
    ansible_distribution == 'Amazon'
  copy: >
    src= {{ item.option }}
    dest= {{ item.value }}
    owner=root
    group=root
    mode=0644
    force=yes
  become: yes
  with_items: 
    - { option: jail.local, value: /etc/fail2ban/jail.local }
    - { option: jail.conf, value: /etc/fail2ban/jail.conf }
  notify: 
  - fail2ban | Restart
  tags: 
    - base-install

