---
# handlers file for cloud-init
- name: fail2ban | Restart
  service: name=fail2ban state=restarted 
  become: yes
  tags: base-install

- name: fail2ban | Started
  service: name=fail2ban state=started enabled=yes
  become: yes
  tags: base-install
