---
# tasks file for tf_init
- name: tf_init
  git: 
    repo: https://github.com/tfutils/tfenv.git 
    dest: ~/.tfenv

- name: Adding the path in the bashrc files
    lineinfile: 
      dest: "/root/.bash_profile"
      line: 'export PATH="$HOME/.tfenv/bin:$PATH"'
      insertafter: 'EOF'  
      state: present
 
- name: export config
  shell: "source /root/.bash_profile"

- name: sym link
  file: 
    src: ~/.tfenv/bin/*
    dest: /usr/local/bin
    state: link

- name: tf env 
  shell: "tfenv install 0.13"
  