---
# tasks file for tf_init
- name: tf_init
  git: 
    repo: https://github.com/tfutils/tfenv.git 
    dest: ~/.tfenv

- name: export config
  shell: "echo 'export PATH="$HOME/.tfenv/bin:$PATH"' >> ~/.bash_profile"

- name: sym link
  file: 
    src: ~/.tfenv/bin/*
    dest: /usr/local/bin
    state: link

- name: tf env 
  shell: "tfenv install 0.13"
  